#  http://wiki.ros.org/amcl
min_particles:             100  # Minimalna dopuszczalna liczba cząstek
max_particles:             3000 # Maksymalna dopuszczalna liczba cząstek
kld_err:                   0.002 # Błąd maksymalny między rozkładem prawdziwym a rozkładem oszacowanym
update_min_d:              0.10 # Ruch translacyjny wymagany przed wykonaniem aktualizacji filtra. [m]
update_min_a:              0.05 # Ruch obrotowy wymagany przed wykonaniem aktualizacji filtra.[rad]
resample_interval:         2    # Liczba aktualizacji filtra wymaganych przed ponownym próbkowaniem
transform_tolerance:       0.5  # Tolerancja opóźnienia transformacji [s]
recovery_alpha_slow:       0.001
recovery_alpha_fast:       0.01
initial_pose_x:            0.0
initial_pose_y:            0.0
initial_pose_a:            0.0
gui_publish_rate:          5.0 # Maksymalna szybkość [Hz], z jaką skany i ścieżki są publikowane dla wizualizacji, -1.0 do wyłączenia.

laser_max_range:           10. # Maksymalny zasięg skanowania, który ma być brany pod uwagę; -1.0 spowoduje, że zostanie użyty maksymalny zasięg podany przez laser.
laser_max_beams:           30 # Ile równomiernie rozłożonych wiązek w każdym skanie ma zostać wykorzystanych podczas aktualizacji filtra.
laser_z_hit:               0.95 # Waga mieszanki dla części z_hit modelu.
laser_z_short:             0.05 # Waga mieszanki dla części z_short modelu.
laser_z_max:               0.05 # Waga mieszanki dla części z_max modelu.
laser_z_rand:              0.5  # Waga mieszanki dla części z_rand modelu.
laser_sigma_hit:           0.2 # Odchylenie standardowe dla modelu gaussowskiego użytego w części z_hit.
laser_lambda_short:        0.1 # Parametr rozkładu wykładniczego dla części z_short modelu.
laser_likelihood_max_dist: 2.0 # Maksymalna odległość do wykonania inflacji przeszkód na mapie, do wykorzystania w modelu likelihood_field.
laser_model_type:          likelihood_field # Który model zastosować: beam, likelihood_field, likelihood_field_prob

odom_model_type:           omni
odom_alpha1:               0.01 # Oczekiwany szum w estymacji obrotu odometrii, pochodzący od składowej obrotowej ruchu robota.
odom_alpha2:               0.01 # Oczekiwany szum w estymacji obrotu odometrii pochodzący od translacyjnej składowej ruchu robota.
odom_alpha3:               0.01 # Oczekiwany szum w estymacji translacji odometrii, pochodzący od translacyjnej składowej ruchu robota.
odom_alpha4:               0.01 # Oczekiwany szum w estymacji translacji odometrii, pochodzący od składowej obrotowej ruchu robota.
odom_alpha5:               0.01 # Parametr szumu związany z interpretacją (używany tylko wtedy, gdy model jest "omni").
odom_frame_id:             odom
base_frame_id:             base_footprint
