#  http://wiki.ros.org/amcl
min_particles:             100  # Minimalna dopuszczalna liczba cząstek
max_particles:             3000 # Maksymalna dopuszczalna liczba cząstek
kld_err:                   0.02 # Błąd maksymalny między rozkładem prawdziwym a rozkładem oszacowanym
update_min_d:              0.20 # Ruch translacyjny wymagany przed wykonaniem aktualizacji filtra. [m]
update_min_a:              0.50 # Ruch obrotowy wymagany przed wykonaniem aktualizacji filtra.[rad]
resample_interval:         2    # Liczba aktualizacji filtra wymaganych przed ponownym próbkowaniem
transform_tolerance:       0.5  # Tolerancja opóźnienia transformacjiiiiiii [s]
recovery_alpha_slow:       0.001
recovery_alpha_fast:       0.01
initial_pose_x:            0.0
initial_pose_y:            0.0
initial_pose_a:            0.0
gui_publish_rate:          10.0 # Maksymalna szybkość [Hz], z jaką skany i ścieżki są publikowane dla wizualizacji, -1.0 do wyłączenia.

laser_max_range:           12.
laser_max_beams:           200
laser_z_hit:               0.5
laser_z_short:             0.05
laser_z_max:               0.05
laser_z_rand:              0.5
laser_sigma_hit:           0.2
laser_lambda_short:        0.1
laser_likelihood_max_dist: 2.0
laser_model_type:          likelihood_field # Który model zastosować: beam, likelihood_field, likelihood_field_prob

odom_model_type:           omni
odom_alpha1:               0.01 # Oczekiwany szum w estymacji obrotu odometrii, pochodzący od składowej obrotowej ruchu robota.
odom_alpha2:               0.01 # Oczekiwany szum w estymacji obrotu odometrii pochodzący od translacyjnej składowej ruchu robota.
odom_alpha3:               0.01 # Oczekiwany szum w estymacji translacji odometrii, pochodzący od translacyjnej składowej ruchu robota.
odom_alpha4:               0.01 # Oczekiwany szum w estymacji translacji odometrii, pochodzący od składowej obrotowej ruchu robota.
odom_alpha5:               0.01 # Parametr szumu związany z interpretacją (używany tylko wtedy, gdy model jest "omni").
odom_frame_id:             odom
base_frame_id:             base_footprint
