obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
#  min_x: -0.3
#  max_x: 0.3
#  min_y: -0.25
#  max_y: 0.25

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: rp_lidar_a1, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
