DWAPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 0.22   # Maksymalna prędkość poruszania się robota w osi X w [m/s]  (wartość domyślna 0.55)
  min_vel_x: -0.22  # Minimalna prędkość poruszania się robota w osi X w [m/s]  (w.d. 0.0)

  max_vel_y: 0.0  # Maksymalna prędkość poruszania się robota w osi Y w [m/s] (w.d. 0.1)
  min_vel_y: 0.0  # Minimalna prędkość poruszania się robota w osi Y w [m/s]  (w.d. -0.1)

  # The velocity when robot is moving in a straight line
  max_vel_trans:  0.22  # Maksymalna bezwględna prędkość poruszania się robota w przypadku poruszania się po linii prostej w [m/s] (w.d. 0.55)
  min_vel_trans:  0.11  # Minimalna bezwzględna prędkość poruszania się robota w przypadku poruszania się po linii prostej w [m/s]  (w.d. 0.1)

  max_vel_theta: 1.0 # Maksymalna bezwzględna prędkość kątowa robota w [rad/s] (w.d. 1.0)
  min_vel_theta: 0.2 # Minimalna bezwzględna prędkość kątowa robota w [rad/s]  (w.d. 0.4)

  acc_lim_x: 2.5  # Maksymalna wartość przyśpieszenia robota w osi X w [m/s^2] (w.d. 2.5)
  acc_lim_y: 0.0  # Maksymalna wartość przyśpieszenia robota w osi Y w [m/s^2]  (w.d. 2.5)
  acc_lim_theta: 1.0 # Maksymalna wartość przyśpieszenia kątowego robota w [rad/s^2]  (w.d. 3.2)

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.15 # Wartość dopuszczalnego błędu odlegości w przypadku dotarcia do celu w osi X oraz w osi Y w metrach  (w.d. 0.1)
  yaw_goal_tolerance: 3.14 # Wartość dopuszczalnego błędu orientacji w przypadku dotarcia do celu w radianach (w.d. 0.05)
  latch_xy_goal_tolerance: false  # W przypadku ustawienia tej wartości na true gdy robot dotrze do celu zacznie obracać się w miejscu,
  # nawet jeżeli spowoduje to oddalenie się od celu o dopuszczalne wartości (w.d. false)

  # Forward Simulation Parameters
  sim_time: 1.5 # Wartość czasu do symulowania trajektorii robota do przodu w sekundach (w.d. 1.7)
  vx_samples: 20  # Liczba próbek wykorzystywana podczas badania przestrzeni prędkości w osi X (w.d. 3)
  vy_samples: 0   # Liczba próbek wykorzystywana podczas badania przestrzeni prędkości w osi Y (w.d. 0)
  vth_samples: 40 # Liczba próbek wykorzystywana podczas badania przestrzeni prędkości kątowej (w.d. 20)
  controller_frequency: 10.0 # Częstotliwość odświeżania sterownika DWAPlannerROS w Hz (w.d. 20)
  # W przypadku użyciu z move_base można jeSdynie ustawić ten parametr w tamtym miejscu, a w tym pozostawić nieustawiony

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0  # Waga dla tego jak blisko robot powinien trzymać się podanej ścieżki
  goal_distance_bias: 20.0  # Waga dla tego w jakim stopniu robot powinien próbować osiągnąć swój cel lokalny, kontroluje również prędkość
  occdist_scale: 0.02       # Waga dla tego jak bardzo robot powinien starać się omijać przeszkody
  forward_point_distance: 0.325 # Odległość od punktu środkowego robota do umieszczenia dodatkowego punktu do osiągnięcia, w metrach (w.d. 0.325)
  stop_time_buffer: 0.2 # Czas przez jaki robot musi się zatrzymać przed kolizją, aby trajektoria została uznana za prawidłową, w sekundahch (w.d. 0.2)
  scaling_speed: 0.25 # Wartość bezwzględna prędkości przy której należy rozpocząć skalowanie śladu robota w [m/s] (w.d. 0.25)
  max_scaling_factor: 0.2 # Wartość maksymalna współczynnika skalowania śladu robota (w.d. 0.2)

  # Funkcja kosztu obliczana jest następująco:
  #  cost =
  #  path_distance_bias * (odległość do ścieżki z punktu końcówego trajektorii robota w metrach (w.d. 32.0))
  #  + goal_distance_bias * (odległość do celu lokalnego z punktu końcowego trajektorii robota w metrach (w.d. 24.0))
  #  + occdist_scale * (wartość maksymalna kosztu przeszkody wzdłuż trajektorii robota zawarta w [0-254] (w.d. 0.01))

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # Wartość odległości w metrach jaką musi przebyć robot, aby flagi oscylacji zostały zresetowane (w.d. 0.05)

  # Debugging
  publish_traj_pc : true  # Czy ma być publikowana trajektoria robota
  publish_cost_grid_pc: true  # Czy ma być publikowana siatka kosztów wykorzystywana przez algorytm, w przypadku ustawienia wartości na true
  # sensor_msgs/PointCloud2 będzie dostępny na temacie ~<name>/cost_cloud

  track_unknown_space: false