# plik konfiguracyjny gmapping

# Ustawienia ogólne
map_update_interval: 1.0 # Częstotliwość aktualizacji mapy
maxUrange: 10.0 # Maksymalny zasięg czujnika laserowego
sigma: 0.05 # Odchylenie standardowe związane z obserwacjami

base_frame: "base_footprint" # Ramka robota
odom_frame: "odom" # Ramka odometrii
