teleop:
  # pb wired
#    planar:
#      type: topic
#      message_type: geometry_msgs/Twist
#      topic_name: cmd_vel
#      deadman_buttons: [5]
#      axis_mappings:
#        -
#          target: linear.x
#          axis: 1
#          scale: 1.0
#          offset: 0
#        -
#          target: linear.y
#          axis: 0
#          scale: 1.0
#          offset: 0
#        -
#          target: angular.z
#          axis: 3
#          scale: 1.0
#          offset: 0
  # white bluetooth
  planar:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        target: linear.x
        axis: 1
        scale: 1.0
        offset: 0
      -
        target: linear.y
        axis: 0
        scale: 1.0
        offset: 0
      -
        target: angular.z
        axis: 2
        scale: 1.0
        offset: 0

  # joy
#  planar:
#    type: topic
#    message_type: geometry_msgs/Twist
#    topic_name: cmd_vel
#    deadman_buttons: [0]
#    axis_mappings:
#      -
#        target: linear.x
#        axis: 1
#        scale: 1.0
#        offset: 0
#      -
#        target: linear.y
#        axis: 0
#        scale: 1.0
#        offset: 0
#      -
#        target: angular.z
#        axis: 2
#        scale: 1.0
#        offset: 0