local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  static_map: true
  rolling_window: true
  width: 3.5
  height: 3.5
  resolution: 0.05
