local_costmap:
  global_frame: odom # Globalna ramka, w której ma działać costmap
  robot_base_frame: base_footprint # Nazwa bazowego linka robota.

  update_frequency: 5.0 # Częstotliwość w Hz, z jaką ma być aktualizowana mapa.
  publish_frequency: 5.0 # Częstotliwość w Hz, z jaką mają być publikowane informacje o wyświetlaniu mapy.
  transform_tolerance: 0.5  # Określa opóźnienie w danych transformacji (tf), które jest tolerowane w sekundach.

  #  Parametr rolling_window sprawia, że mapa kosztów jest wyśrodkowana wokół robota.
  #  Jeśli ustawimy ten parametr na true, otrzymamy mapę kosztów, która jest zbudowana centralnie wokół robota.
  #  Parametry width , height i resolution to szerokość, wysokość [m] i rozdzielczość [m/cell] costmapy
  static_map: true
  rolling_window: true
  width: 3.5
  height: 3.5
  resolution: 0.05
